### ISSUE TITLE
Migration from Less - handling of double slash comments

### ISSUE THREAD

**Issue by chrisdeeming** [peteboere/css-crush#102]
This isn't a dealbreaker, but thought I'd ask the question.

```less
// avatars
.avatar
{
    // overflow: hidden;
    border-radius: var(--radius-avatar, 100vw);
}
```

With Less, this would be output as:

```css
.avatar
{
    border-radius: var(--radius-avatar, 100vw);
}
```

It looks like we can use the `declaration_preprocess` event to strip out properties that start with `//`.

Are there any events that would enable us to strip out the others, or convert them to CSS comments?
