### ISSUE TITLE
data uris not working

### ISSUE THREAD

**Issue by SgtK** [peteboere/css-crush#37]
Hey

I'm trying to get CSS Crush to generate data uris, but perhaps I'm missing somentihg...

``` php
$css = csscrush_string("
    .mydiv {
        background: data-uri(img/img.png) no-repeat;
    }
");

echo $css;
```

outputs:

``` css
.mydiv {
    background: url(img/img.png) no-repeat;
}
```
